import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
st.title("Sales & Revenue Dashboard")
df = pd.read_csv("sales.csv")   
df["Date"] = pd.to_datetime(df["date"], dayfirst=True)
total_revenue = df["revenue"].sum()
total_sales = df["sales"].sum()
avg_revenue = total_revenue / df["date"].nunique()
st.subheader("Key Performance Indicators")
col1, col2, col3 = st.columns(3)
col1.metric("Total Revenue", total_revenue)
col2.metric("Total Sales", total_sales)
col3.metric("Avg Daily Revenue", round(avg_revenue, 2))
st.subheader("Daily Revenue Trend")
daily_revenue = df.groupby("date")["revenue"].sum()
fig1, ax1 = plt.subplots()
ax1.plot(daily_revenue.index, daily_revenue.values, marker="o")
ax1.set_xlabel("Date")
ax1.set_ylabel("Revenue")
plt.xticks(rotation=45) 
st.pyplot(fig1)
st.subheader("Product Revenue")
product_revenue = df.groupby("product")["revenue"].sum()
fig2, ax2 = plt.subplots()
ax2.bar(product_revenue.index, product_revenue.values)
st.pyplot(fig2)